name: Spark Lint & Test

on:
  push:
    branches: [main]
    paths:
      - 'spark_jobs/**'
      - 'tests/**'
      - 'ingestion/**'
      - '.github/workflows/spark_lint_test.yml'
  pull_request:
    branches: [main]
    paths:
      - 'spark_jobs/**'
      - 'tests/**'
      - 'ingestion/**'
      - '.github/workflows/spark_lint_test.yml'
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write


jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          pip install pyspark==3.5.3 \
            pyarrow==15.0.0 \
            pandas==2.2.0 \
            pytest==8.3.0 \
            black==24.4.2 \
            flake8==7.0.0 \
            google-cloud-bigquery==3.42.2

      - name: Black format check
        run: black --check spark_jobs/ ingestion/ tests/

      - name: Flake8 lint
        run: flake8 spark_jobs/ ingestion/ tests/ --max-line-length=100 --extend-ignore=E203,W503

      - name: Run pytest
        run: python -m pytest tests/spark/ -v
  deploy-to-gcs:
    needs: lint-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/476625998096/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: 'github-ci-dbt@banking-data-platform-500108.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build spark_jobs.zip
        run: |
          zip -r spark_jobs.zip spark_jobs/ -x "*.pyc" -x "*__pycache__*"
          echo "--- Verify critical files included ---"
          unzip -l spark_jobs.zip | grep -E "rules.py|conform_trips.py|run_local.py"

      - name: Deploy to GCS
        run: |
          gsutil cp spark_jobs/jobs/conform_trips.py \
            gs://nyc-taxi-raw-banking-500108/jobs/conform_trips.py
          gsutil cp spark_jobs.zip \
            gs://nyc-taxi-raw-banking-500108/jobs/spark_jobs.zip

      - name: Verify upload
        run: |
          gsutil ls -L gs://nyc-taxi-raw-banking-500108/jobs/spark_jobs.zip | grep -i "Update time"
